services:
  user_service:
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    ports:
      - "50051:50051"
    env_file:
      - ./services/user/.env
    depends_on:
      postgres_user:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - user_net
      - service_net

  task_service:
    build:
      context: .
      dockerfile: ./services/task/Dockerfile
    ports:
      - "50052:50052"
    env_file:
      - ./services/task/.env
    depends_on:
      postgres_task:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - task_net
      - service_net

  dtms:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    networks:
      - service_net
    depends_on:
      user_service:
        condition: service_healthy
      task_service:
        condition: service_healthy

  postgres_user:
    image: postgres:latest
    environment:
      POSTGRES_USER: bittu
      POSTGRES_PASSWORD: bittu
      POSTGRES_DB: users
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
      - ./initdb/init-postgres_user.sql:/docker-entrypoint-initdb.d/init-postgres_user.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bittu -d users"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - user_net

  postgres_task:
    image: postgres:latest
    environment:
      POSTGRES_USER: bittu
      POSTGRES_PASSWORD: bittu
      POSTGRES_DB: tasks
    volumes:
      - postgres-task-data:/var/lib/postgresql/data
      - ./initdb/init-postgres_task.sql:/docker-entrypoint-initdb.d/init-postgres_task.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bittu -d tasks"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - task_net

volumes:
  postgres-user-data:
  postgres-task-data:

networks:
  service_net:
  user_net:
  task_net:
